# Generated by Django 4.1.2 on 2022-11-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_alter_like_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10),
        ),
    ]
