# Generated by Django 4.1.2 on 2022-12-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0026_alter_like_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Unlike', 'Unlike'), ('Like', 'Like')], default='Like', max_length=10),
        ),
    ]
