# Generated by Django 4.1.2 on 2022-12-11 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_profile_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date',
        ),
    ]
