# Generated by Django 4.1.2 on 2022-10-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='context',
            field=models.TextField(max_length=1000),
        ),
    ]
