# Generated by Django 4.1.2 on 2022-11-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_alter_diet_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='image',
            field=models.ImageField(default='diet_pics/default.png', upload_to='diet_pics'),
        ),
    ]
