# Generated by Django 4.1.2 on 2022-11-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_diet_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
