# Generated by Django 4.1.2 on 2022-12-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0007_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='context',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
