# Generated by Django 4.1.2 on 2022-12-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0008_alter_review_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='context',
            field=models.TextField(max_length=1000),
        ),
    ]
