# Generated by Django 4.1.2 on 2022-12-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0009_alter_review_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
