# Generated by Django 4.1.2 on 2022-12-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0010_review_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
